# Generated by Django 4.0.4 on 2022-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='profile_picture',
            field=models.FileField(default=2, upload_to='documents'),
            preserve_default=False,
        ),
    ]
