# Generated by Django 4.0.4 on 2022-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_student_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_table',
            old_name='student_department',
            new_name='department',
        ),
        migrations.AddField(
            model_name='student_table',
            name='logger_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
