# Generated by Django 4.0.4 on 2022-05-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_rename_student_department_student_table_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachingstaff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_faculty', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
