# Generated by Django 4.0.4 on 2022-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_teachingstaff_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonteachingstaff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=100)),
                ('pay_level', models.CharField(max_length=100)),
                ('Regular_temporary', models.CharField(max_length=100)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
