# Generated by Django 4.0.4 on 2022-05-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_nonteachingstaff_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonteachingstaff_table',
            old_name='Regular_temporary',
            new_name='salary',
        ),
    ]
