# Generated by Django 4.0.4 on 2022-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_researchdepartment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='internationalrelations_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_student', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
